### PR TITLE
Update picozero.py

### PR DESCRIPTION
**Pull request by DaveAtKitronik**
An 'f' appears to have snuck in on line 367.

### CODE REVIEW

**Comment by martinohanlon** [comment]
Isnt this because it uses an f string to format the error message.

**Comment by DaveAtKitronik** [comment]
gave me the following error in Thonny:
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "picozero.py", line 367
SyntaxError: invalid syntax
>>> %Run -c $EDITOR_CONTENT

removing the 'f' made the error go away.  I haven't looked in detail at the lib, just thought I should let someone know.

**Comment by martinohanlon** [comment]
Interesting. I wonder if this is a discrepancy with micropython versions. Are you running the latest pico micropython version from https://micropython.org/download/rp2-pico/rp2-pico-latest.uf2

**Comment by martinohanlon** [comment]
The PR wont fix the issue, as the string wont be formatted correctly when the error occurs. However... it does raise an issue which assuming this is a micropython version issue, maybe the f string should be removed and simply string concatenation which would have wider support be used.

**Comment by DaveAtKitronik** [comment]
currently on V1.16 -  I don't tend to update Pico unless I need to - usually I put whatever is the latest on when I first run it. I suspect most educators would be the same.
I will try an update and see.

**Comment by DaveAtKitronik** [comment]
Put the 'f' back in on my local copy, updated to 1.18 adn no error. So it like it is microPython version related.

**Comment by martinohanlon** [comment]
Thanks a lot for the test and info @DaveAtKitronik . I have raised issue #46 so will close this PR. Thanks for letting us know.

**Pull request closed without merging**
